$(document).ready(function(){
if(window.location == 'https://azure.instructure.com/login'){
  var n=$("#modal-box"),e="<ul style='width:625px;margin:20px auto 0px;'><li class='menu-item'><a href='https://azure.instructure.com/courses/6/wiki/system-requirements' class='menu-item-no-drop' style='font-weight:bold;font-size: 16px;' target='_blank'>System Requirements</a></li><li class='menu-item'><a href='https://azure.instructure.com/courses/8/wiki/faculty-staff-resources' class='menu-item-no-drop' target='_blank' style='font-weight:bold;font-size: 16px;'>Faculty/Staff Support</a></li><li class='menu-item'  ><a href='https://azure.instructure.com/courses/7/wiki/student-resources' class='menu-item-no-drop' target='_blank' style='font-weight:bold;font-size: 16px;'>Student Support</a></li></ul></br>",
  
  m=$("#footer-links"),f="<span id='footer-link' style='float:right;'><a href='http://www.azure.edu/' target='_blank'>Azure Home</a><a href='https://www.facebook.com/foreigngradmd' target='_blank'>Facebook</a><a href='https://twitter.com/azurecollege' target='_blank'>Twitter</a></span>",h="<span id='footer-link'><a href='http://www.azure.edu/' target='_blank'>Azure Home</a><a href='https://www.facebook.com/foreigngradmd' target='_blank'>Facebook</a><a href='https://twitter.com/azurecollege' target='_blank'>Twitter</a></span>",  
  o=$("#calendar_menu_item"),g="<li class='menu-item'><a href='https://login.microsoftonline.com/login.srf?wa=wsignin1.0&rpsnv=2&ct=1389510024&rver=6.1.6206.0&wp=MBI_SSL&wreply=https:%2F%2Foutlook.office365.com%2Fowa%2F&id=260563&whr=azure.edu&CBCXT=out#path=/mail' class='menu-item-no-drop' target='_blank'>Azure Email</a></li><li class='menu-item'><a href='http://search.ebscohost.com/' target='_blank'>Azure Library</a></li>";$(e).insertAfter($(n)),$(f).insertAfter($(m)),$(g).insertAfter($(o))}else{var n=$("#modal-box"),e="<ul style='width:625px;margin:20px auto 0px;'><li class='menu-item'><a href='https://azure.instructure.com/courses/6/wiki/system-requirements' class='menu-item-no-drop' style='font-weight:bold;font-size: 16px;' target='_blank'>System Requirements</a></li><li class='menu-item'><a href='https://azure.instructure.com/courses/8/wiki/faculty-staff-resources' class='menu-item-no-drop' target='_blank' style='font-weight:bold;font-size: 16px;'>Faculty/Staff Support</a></li><li class='menu-item'  ><a href='https://azure.instructure.com/courses/7/wiki/student-resources' class='menu-item-no-drop' target='_blank' style='font-weight:bold;font-size: 16px;'>Student Support</a></li></ul></br>",
  
  m=$("#footer-links"),f="<span id='footer-link' style='float:right;'><a href='http://www.azure.edu/' target='_blank'>Azure Home</a><a href='https://www.facebook.com/foreigngradmd' target='_blank'>Facebook</a><a href='https://twitter.com/azurecollege' target='_blank'>Twitter</a></span>",h="<span id='footer-link'><a href='http://www.azure.edu/' target='_blank'>Azure Home</a><a href='https://www.facebook.com/foreigngradmd' target='_blank'>Facebook</a><a href='https://twitter.com/azurecollege' target='_blank'>Twitter</a></span>",  
  o=$("#calendar_menu_item"),g="<li class='menu-item'><a href='https://login.microsoftonline.com/login.srf?wa=wsignin1.0&rpsnv=2&ct=1389510024&rver=6.1.6206.0&wp=MBI_SSL&wreply=https:%2F%2Foutlook.office365.com%2Fowa%2F&id=260563&whr=azure.edu&CBCXT=out#path=/mail' class='menu-item-no-drop' target='_blank'>Azure Email</a></li><li class='menu-item'><a href='http://search.ebscohost.com/' target='_blank' class='menu-item-no-drop'>Azure Library</a></li>";$(e).insertAfter($(n)),$(h).insertAfter($(m)),$(g).insertAfter($(o))}} );
